name: 'Pipeline package lambda python'
description: 'package lambda python aws'
inputs:
  PATH_TO_ROOT: 
    description: 'Path to root'
    required: true

runs:
  using: "composite"
  steps:
    - name: Path to requirements.txt
      run: echo ${{ inputs.PATH_TO_ROOT }}.
      shell: bash
    
    - name: Checkout
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
        cache: 'pip'
    
    - name: Install dependencies and zip package    
      run: |
        python -m pip install --upgrade pip
        cd ${{ inputs.PATH_TO_ROOT }}
        pip install -r requirements.txt -t .
        zip -r package.zip *    
      shell: bash

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: package.zip
        path: ${{ inputs.PATH_TO_ROOT }}/package.zip
      if: ${{ always() }}